services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel-app
        volumes:
            - ./:/var/www
        depends_on:
            - db
            - rabbitmq
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: laravel-nginx
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: laravel-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

    rabbitmq:
        image: rabbitmq:3-management
        container_name: laravel-rabbitmq
        ports:
            - "5672:5672"   # RabbitMQ protocol
            - "15672:15672" # RabbitMQ dashboard
        networks:
            - laravel

    adminer:
        image: adminer
        restart: always
        networks:
            - laravel
        ports:
            - "8082:8080"

volumes:
    dbdata:

networks:
    laravel:
        driver: bridge
